### ISSUE TITLE
Benchmarks after pip install candle_lib

### ISSUE THREAD

**Issue by rajeeja** [ECP-CANDLE/candle_lib#1]
It picks up candle from pip, which is a good thing, but there are bugs that we need to fix for it work:
```
(base) jain @ jain ~/projects/Benchmarks/Pilot1/NT3 (develop)
└─ $ ▶ python nt3_baseline_keras2.py 
Importing candle utils for keras
Traceback (most recent call last):
  File "nt3_baseline_keras2.py", line 16, in <module>
    import nt3 as bmk
  File "/home/jain/projects/Benchmarks/Pilot1/NT3/nt3.py", line 61, in <module>
    class BenchmarkNT3(candle.Benchmark):
AttributeError: module 'candle' has no attribute 'Benchmark'
```

**Comment by hyoo** [comment]
this is fixed. set CANDLE_DATA_DIR in your env and try again.

**Comment by rajeeja** [comment]
Yes. It works. Thanks. Will add noise tests soon
