### ISSUE TITLE
Pytorch dependency

### ISSUE THREAD

**Issue by jamieOverbeek** [ECP-CANDLE/candle_lib#9]
After installing candle in a fresh conda environment with 'pip install git+https://github.com/ECP-CANDLE/candle_lib@develop', I try to import candle and get the following error:

>>> import candle
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/homes/joverbeek/.conda/envs/candle_env/lib/python3.7/site-packages/candle/__init__.py", line 165, in <module>
    from .ckpt_pytorch_utils import CandleCkptPyTorch
  File "/homes/joverbeek/.conda/envs/candle_env/lib/python3.7/site-packages/candle/ckpt_pytorch_utils.py", line 11, in <module>
    import torch
ModuleNotFoundError: No module named 'torch'

**Comment by jmohdyusof** [comment]
There was a logic error where a pytorch function was loaded outside the pytorch guard. It should be fixed as of a recent push
